### ISSUE TITLE
[Bug]: got to round 70 not round 75

### ISSUE THREAD

**Issue by UTMUSK** [Zombies-World-Records/issue-tracker#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I got to round 70 not 75. It’s days on the no perks and no tuff nuff it’s 75. But I only got to round 70. Could you please change it to 70? I know it’s a tied record with bober. But I’m fine with a tie. So could you please change it back to a round 70 because that’s when i ended the stream thanks

### Expected behaviour

NA

### Steps to reproduce

NA

### ZWR Account Link

https://zwr.gg/players/VVRNVVNL/

**Comment by iiTsMatthew** [comment]
Good Evening,

Thank you for your issue, however this is not the place to be asking or talking about incorrect records.

Please feel free to make a ticket in our discord server so we can support you further!

You may join the discord at this link:

**https://discord.com/invite/Gn6NecVKXn**

Thank you for continuing to use our website!
