### ISSUE TITLE
Wolrd record counter[Bug]: 

### ISSUE THREAD

**Issue by myrazmo** [Zombies-World-Records/issue-tracker#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Issue with how the world records are being counted on everybody's profile. I personally got up to 200+ for no reason, spykes went from 140+ to 300+. I first thought customs were now being counted but i never played custom ahah. Also NewNickName0 went from 100 to 57. It's just a display issue tho, people actually didn't loose or got records. My bad for making this so long ahah

### Expected behaviour

love you magical

### Steps to reproduce

shesh

### ZWR Account Link

https://zwr.gg/players/bXlSYXptbw/

**Comment by Cody-Orlando-spec** [comment]
Was a temporary issue withe the record counter. This issue should be fixed.

If the problem persits, please create another bug report.
