### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TherealLokixd** [Zombies-World-Records/issue-tracker#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The same player has 2 runs on the solo mauer der toten speed run EE leaderboard which pushed my run off due to him having 2 runs posted on the same board hosting 2 seperate times

### Expected behaviour

the 2nd run to be removed and a proper place given to some one with an appropriate time

### Steps to reproduce

remove run

### ZWR Account Link

https://zwr.gg/players/TE9LSQ/

**Comment by Cody-Orlando-spec** [comment]
Not a bug.

Please create a ticket in the Discord to talk to staff member about this issue.
