### ISSUE TITLE
Add a way to report a run

### ISSUE THREAD

**Issue by NathanGuidry** [Zombies-World-Records/issue-tracker#24]
Many runs often no longer contain footage or can be found against the rules. I'm saying there should be a way for a user to report a run..

**Comment by Drkiller99** [comment]
Hello @NathanGuidry,

Our discord has all that already, we receive reports daily about record footage no longer being available & about runs that have slipped through the cracks of some of our newly trained staff, I’m going to assume you aren’t in our discord so here:
https://discord.gg/ZWR 

-> ticket-support -> report a record on the website.
