### ISSUE TITLE
Submitting videos

### ISSUE THREAD

**Issue by Zannoeaze** [Zombies-World-Records/issue-tracker#26]
Does the link have to be a certain format? I copy the link from the video on YouTube but says the link is invalid but I can click the link I put in and it takes me to the video. Any thoughts on why it does that?

**Comment by Drkiller99** [comment]
No, do you mind sending me the exact link you used? It should work perfectly fine, I've just tested a YouTube link with no complications. 😅

**Comment by Drkiller99** [comment]
@Zannoeaze

**Comment by Zannoeaze** [comment]
https://youtu.be/qOpFBEpEPns

**Comment by Zannoeaze** [comment]
Don't know if it's cause I'm copying the mobile link since I'm on my phone but tried the other videos of the earlier rounds but said they were invalid links as well. Not really a big deal since it's not a wr and like 8th all elixirs on voyage lol

**Comment by Drkiller99** [comment]
Please try the following link below: 
- https://www.youtube.com/watch?v=qOpFBEpEPns

If you have any additional issues let us know :)

**Comment by z1khaled1z** [comment]
Hello I suffered from the same problem I have both links but none working
https://www.youtube.com/watch?v=aipyJdk0c8M
https://youtu.be/aipyJdk0c8M
If some one can help me I would appreciate it
Thanks in advance

**Comment by Zannoeaze** [comment]
Still keeps saying invalid video link on any link I try to submit
