### ISSUE TITLE
[Bug]: Overlay Download broken

### ISSUE THREAD

**Issue by DasLaura** [Zombies-World-Records/issue-tracker#6]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Hey <3

the current problem is, when you go to the Downloads section and click on Stream overlay, it just does nothing.
Im not able to get to the next page to download the ZWR Stream Overlay.

I have used different browsers, but the problem still persists
Mainly im using, Mozilla Firefox on current version 101.0.1 (i have also used an fresh install without addons)

### Expected behaviour

Im expecting to get to the download page for the overlay but it kicks me back to the download site, where all other downloads are shown.

### Steps to reproduce

1. Go to downloads
2. Click on stream overlay
3. See that it wont bring you to the Download section for the Overlay

### ZWR Account Link

https://zwr.gg/players/RGFzTGF1cmE/

**Comment by iiTsMatthew** [comment]
Hi,

Thank you for reporting this bug.

We are able to confirm that this is an issue and will be looking into this.

We will give you a response once the issue has been resolved or sorted.

Thank you.

**Comment by Cody-Orlando-spec** [comment]
Invalid redir. Issue has been fixed

/Resolved
