### ISSUE TITLE
[Bug]: YouTube video not valid

### ISSUE THREAD

**Issue by NYlprimate** [Zombies-World-Records/issue-tracker#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to upload YouTube video of proof for spot number 10 on the leaderboards, but the video says it isn’t valid even though it’s unlisted 

### Expected behaviour

YouTube video can’t be uploaded due to invalid video

### Steps to reproduce

I don’t know how to fix it

### ZWR Account Link

I don’t have one

**Comment by iiTsMatthew** [comment]
Good Evening,

I am unable to confirm if this is a reproducible bug and in fact if it doesn't allow you to upload it.

What I can suggest from here on out is to make a ticket on our Discord server so we can assist you further!

You may join the discord at this link:

**https://discord.com/invite/Gn6NecVKXn**

Thank you for continuing to use our website!
